root = "."
tmp_dir = "bin"

[build]
  pre_cmd = ["templ generate"]
  cmd = "go build -o ./bin/poolvibes ."
  bin = "./bin/poolvibes"
  args_bin = ["serve"]
  include_ext = ["go", "templ"]
  exclude_dir = ["bin", "vendor", "e2e", "docs", "node_modules", "migrations"]
  exclude_regex = ["_templ\\.go$", "_test\\.go$"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
